"""Tests over the committed public-domain seed fixtures.

Unlike the copyrighted Calibre fixtures (gitignored, skipped when absent), these
seeds are committed, so these tests always run — including in CI on a fresh
clone. The seeds are generated by tests/fixtures/public-domain/make_seeds.py
from public-domain Dickens text.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from colophon.validator import validate

SEEDS = Path(__file__).parent / "fixtures" / "public-domain"


def test_seed_fixtures_are_committed():
    """If these are missing, regenerate with make_seeds.py — they must be in-repo."""
    assert (SEEDS / "pd-clean-epub3.epub").exists()
    assert (SEEDS / "pd-broken-toc-epub2.epub").exists()


def test_clean_seed_validates_clean():
    issues = validate(SEEDS / "pd-clean-epub3.epub").issues
    assert issues == [], f"clean baseline should have no issues, got {[i.code for i in issues]}"


def test_broken_toc_seed_flags_ncx008():
    codes = {i.code for i in validate(SEEDS / "pd-broken-toc-epub2.epub").issues}
    assert "NCX008" in codes


@pytest.mark.parametrize("name", ["pd-clean-epub3.epub", "pd-broken-toc-epub2.epub"])
def test_seed_is_valid_zip_with_mimetype_first(name):
    import zipfile

    with zipfile.ZipFile(SEEDS / name) as z:
        names = z.namelist()
        assert names[0] == "mimetype"  # OCF: mimetype must be the first entry
        assert z.read("mimetype") == b"application/epub+zip"
