"""Fetch the curated public-domain corpus listed in corpus.json.

Downloads each book into tests/fixtures/public-domain/_fetched/ (gitignored), so
the repo stays lean while a larger real-world corpus is available on demand.
Already-present files are skipped, so re-running is cheap.

    python tests/fixtures/public-domain/fetch.py            # fetch all
    python tests/fixtures/public-domain/fetch.py dubliners  # fetch matching slugs

The committed seed EPUBs (pd-*.epub) are generated by make_seeds.py, not fetched.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
DEST = HERE / "_fetched"
MANIFEST = HERE / "corpus.json"
# Gutenberg/Standard Ebooks are friendlier to a real UA than the default.
_UA = "Colophon-fixture-fetcher/0.1 (+https://github.com/colophon-epub/colophon)"


def main(filters: list[str]) -> int:
    books = json.loads(MANIFEST.read_text(encoding="utf-8"))["books"]
    DEST.mkdir(parents=True, exist_ok=True)
    failures = 0
    for book in books:
        slug = book["slug"]
        if filters and not any(f.lower() in slug.lower() for f in filters):
            continue
        out = DEST / slug
        if out.exists():
            print(f"  skip   {slug} (already present)")
            continue
        try:
            req = urllib.request.Request(book["url"], headers={"User-Agent": _UA})
            with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310 (curated URLs)
                data = resp.read()
            out.write_bytes(data)
            print(f"  fetch  {slug} ({len(data):,} bytes) <- {book['source']}")
        except Exception as exc:  # noqa: BLE001 - report and continue
            failures += 1
            print(f"  FAIL   {slug}: {type(exc).__name__}: {exc}")
            print(f"         url: {book['url']}  (edit corpus.json if it has rotted)")
    if failures:
        print(f"\n{failures} download(s) failed; the rest are in {DEST}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
